defaults:
  - polygraph_eval_sciq_default_instruct
  - top1_processing_sciq
  - default_blackbox_estimators
  - _self_

experiment_name: sciq_empirical_baselines

dataset: ['sciq']
description: "Here's a short context:\n\n{context} (End of context)\n\nProvide your best guess for the following question. Give ONLY the guess, no other words or explanation.\n\nFor example:\n\nGuess: <most likely guess, as short as possible; not a complete sentence, just the guess!>"
few_shot_prompt: "Question: {question}\nGuess: {answer}"
prompt: "Question: {question}\n"
max_new_tokens: 20
generation_params:
  extra_body:
    chat_template_kwargs: 
      enable_thinking: False
  stop_strings:
    - "\n"

stat_calculators:
  - auto
