- name: MaximumSequenceProbability
- name: Perplexity
- name: MeanTokenEntropy
- name: MeanPointwiseMutualInformation
- name: SelfCertainty
- name: MeanConditionalPointwiseMutualInformation 
- name: ClaimConditionedProbability
- name: PTrue